### ISSUE TITLE
Error code 0

### ISSUE THREAD

**Issue by alkuznetsov** [k-shym/URFAClient#10]
При попытки вызвать любую функцию (например rpcf_get_users_list) получаем ответ - Error code 0
Самое интересное что с локального компа (Win 8, apache 24 и php 5.6) все работает без проблем.
Ошибка появляется только на продакшин серверах - OC Debian 8 nginx и php 5.6 (сборки php везде одинаковы)
UTM работает на FreeBSD  9.2-STABLE FreeBSD 9.2-STABLE  amd64
Не подскажите описание ошибки или где можно прочитать?

**Comment by k-shym** [comment]
Скорее всего не подключили какой-то модуль PHP (например openssl). Выполните в консоли `php -m` и сравните списки. Так же в момент вызова функции посмотрите логи UTM5.

**Comment by alkuznetsov** [comment]
Спасибо за ответ, сверим конфиги, в логах UTM5 вот такие:
Jul 28 13:53:12  Info  : 8dd9c00 RPCConn[SSL]a.kuznetsov@78.46.25.165: Access granted to [SSL]a.kuznetsov@78.46.25.165 (UID: -13)
SSL error lines: 34508479488:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:/usr/src/secure/lib/libssl/../../../crypto/openssl/ssl/s3_pkt.c:301:

**Comment by k-shym** [comment]
Какая версия UTM5? Используйте по возможности протокол TLS.
