### ISSUE TITLE
Error code 0 

### ISSUE THREAD

**Issue by Cramac** [k-shym/URFAClient#14]
Приветствую.
Обновился какой то пакет на сервере, теперь не идет коннект до UTM.
Array ( [0] => 2017.08.19 12:46:43 ERROR: rpcf_core_version( Array ( ) ): Error code 0 )
на стороне УТМ пишет что ошибка ssl соединения, на стороне урфы, пишет error 0.
Такое было когда в конфиге указывал ssl, но тут у меня tls

Пробовал на php 5.6 / 7.1
>openssl version
OpenSSL 1.1.0f  25 May 2017

коннект
$urfa = URFAClient::init(array(
    'login'    => 'init',
    'password' => 'pass',
    'address'  => host,
    'timeout'  => 30,
    'protocol' => 'tls',
    'log'      => true,
));

**Comment by Cramac** [comment]
проблема решена путем отката версии ПХП и используемых библиотек от openssl

**Comment by vnt-83** [comment]
Похожая проблема. На php7 не соединяется с урфой. На php5 всё нормально. Но php5 постепенно уходит в прошлое. Нельзя ли добавить поддержку php7?

**Comment by k-shym** [comment]
Дело не в php7, а в библиотеке openssl, с версии 1.1 появилась проблема, даже не работает официальный клиент на java, в логах я получаю ошибку:

> new SSL connection accepted uses (NONE) cipher

У меня решения пока нет.

**Comment by Cramac** [comment]
поддерживаю. проблема именно в openssl

**Comment by s-filko** [comment]
Приветствую. Подсткажите, у меня такая-же проблема как и у автора топика.
PHP7, пробую использовать TLS протокол.

Инициализация `URFAClient::init()` проходит без ошибок, а далее при попытке выполнить любой метод возвращается `Error code 0`.

Можно ли обойтись без SSL?

**Comment by k-shym** [comment]
Собираем PHP с OpenSSL 1.0.*

**Comment by k-shym** [comment]
Начиная с версии ядра UTM-5.3-005-update2, поддерживается версия OpenSSL 1.1
