### ISSUE TITLE
Ошибка в вызове функции rpcf_add_periodic_slink_ex

### ISSUE THREAD

**Issue by DEN1111** [k-shym/URFAClient#16]
Version:5.3-002

Если прописать tariff_link_id функция перестает работать! При тестировании на версии 5.3-003 все хорошо!

**Comment by k-shym** [comment]
Функция в этих версиях не менялась, что в логах ядра биллига?

**Comment by DEN1111** [comment]
Сорри! Сам ошибся! Вопрос снимается! Забивал id тарифа а надо было Id связки! Спасибо за внимание!
