### ISSUE TITLE
v1.3.0 Изменения

### ISSUE THREAD

**Issue by EvgeniyKorepov** [k-shym/URFAClient#20]
Спасибо за новую версию!
Можно пояснить вот эти изменения:
- Доработан анализ узла output
- Добавлена обработка тэга set

Они как то скажутся на формате результатов функций?
Заранее благодарю!

**Comment by k-shym** [comment]
Принцип и структура не изменилась, могут добавится элементы массива в результате запроса. Поэтому совместимость с предыдущей версией осталась.
