### ISSUE TITLE
Бесконечная рекурсия

### ISSUE THREAD

**Issue by MuVO** [k-shym/URFAClient#24]
Пытаюсь выполнить поиск через `rpcf_search_users_new`

пример:
```php
            ->rpcf_search_users_new([
                'select_type' => 0,
                'patterns_count' => [
                    [
                        'what' => 2,
                        'criteria_id' => 3,
                        'pattern' => 'test1',
                    ]
                ],
            ]);
```

скрипт при попытке выполнения выпадает в OOM

путём дебага и траблшутинга выяснил, что фейлится [вот в этом](https://github.com/k-shym/URFAClient/blob/c9f82d721fc5cbd397835784e6cf0cf523b743f7/classes/URFAClient/API.php#L336) месте

Признаюсь честно: я логикой так и не допёр, что там должно происходить, но __в моём__ случае в `$count` обнаруживается не целое число, а массив, и функция вызывает сама себя, передавая ту же ноду, с которой работала.

такая фигня происходит, похоже, потому что внутри `for` вложен ещё один `for` (в api.xml)

захардкодил костыль
```php
                    if (!is_numeric($count)) {
                        error_log(print_r($count, true));
                        break;
                    }
```
__вроде__ *как-то* работает, но, подозреваю что косячно… может, в случае с массивом надо в функцию передать не _ту же_ ноду, а дочерние?..

в общем, взываю к помощи @k-shym 

 спасибо

**Comment by k-shym** [comment]
Напутал с приоритетами операторов, конечно в `$count` не должен был попасть массив. Спасибо.

Проблема возникла, из-за второго массива `for`, у которого нет счетчика.
