### ISSUE TITLE
Error calling function rpcf_user5_get_promised_payment

### ISSUE THREAD

**Issue by k-integer** [k-shym/URFAClient#27]
Приветствую.
Не работает данная функция. Так же (для теста) пробовал "rpcf_user5_get_tariff_name" - она тоже не работает.
У меня есть подозрение, что это связано с модулем "liburfa-user", но не уверен.
Может я что-то не так запускаю - подскажите, пожалуйста

**Comment by bogdik** [comment]
Это связано скорее всего с ID функции в xml
Так же внимательно смотрите вашу версию xml которую используете

**Comment by k-shym** [comment]
@k-integer привет) нужно больше информации, вывод ошибки, код вызова функции, версия биллинга, лог биллинга в момент вызова функции. Функции **rpcf_user5_*** - клиентские, должна быть авторизация от логина и пароля клиента, вот рабочий пример (тестировал на версии биллинга 5.3-006):
```php
$urfa = URFAClient::init([
    'admin'    => false,
    'login'    => 'user20211226214256',
    'password' => 'pass20211226214256',
    'address'  => '127.0.0.1',
]);

print_r($urfa->rpcf_user5_get_tariff_name(['tariff_id' => 1]));
```
```
Array
(
    [tariff_name] => БУМ
)
```

Напишу тест для функции **rpcf_user5_get_promised_payment** ;)

**Comment by k-shym** [comment]
Добавил тест и протестировал на всех версиях с UTM 5.3
