### ISSUE TITLE
5.3-005-update3

### ISSUE THREAD

**Issue by DEN1111** [k-shym/URFAClient#28]

**Comment by DEN1111** [comment]
Добрый вечер! Обновились с 5.3-002-update2 до 5.3-005-update3. Теперь при подключение в логах ошибка; "SSL connection failed (4), system errno <0>".  В чем может быть проблема?

**Comment by EvgeniyKorepov** [comment]
Попробуйте в файле URFAClient.php заменить
'protocol' => 'ssl'
на
'protocol' => 'tls'

**Comment by DEN1111** [comment]
Пробовал. Та же ошибка.

**Comment by tshadrin** [comment]
Аналогично.

**Comment by tshadrin** [comment]
"SSL connection failed (4), system errno <0>".
Аналогичная проблема при использовании php из докер образа . В debug.log UTM5 видел сообщение о том, что не подхватывается шифрование ADH-RC4-MD5. Попробовал другие варианты шифрования, но не сработало. Тогда просто закоментировал в  URFAClient/classes/URFAClient/Connection.php строку
`stream_context_set_option($context, 'ssl', 'ciphers', 'ADH-RC4-MD5');`
и openssl сам поставил для соединения алгоритм DHE-RSA-AES128-GCM-SHA256, соответственно ошибка устранилась.
Пожалуйста сделайте возможность отключить вызов этой функции

**Comment by EvgeniyKorepov** [comment]
Если бы вы попытались использовать tls вместо ssl, то как раз бы и отключили эту функцию (и устаревший протокол ssl заодно)
`        if ($data['admin'] AND $data['protocol'] !== 'tls')
        {
            stream_context_set_option($context, 'ssl', 'capture_peer_cert', TRUE);
            stream_context_set_option($context, 'ssl', 'local_cert', __DIR__ . '/../../admin.crt');
            stream_context_set_option($context, 'ssl', 'passphrase', 'netup');
            stream_context_set_option($context, 'ssl', 'ciphers', 'SSLv3');
        }
        else
        {
            stream_context_set_option($context, 'ssl', 'ciphers', 'ADH-RC4-MD5');
        }
`

**Comment by k-shym** [comment]
`ssl или tls (доступно с версии UTM-5.3-002-update16) или auto (доступно с версии UTM-5.3-005-update2, работает с OpenSSL 1.1)`

напишите в конфигурации **'protocol' => 'auto'**

**Comment by tshadrin** [comment]
> 
> 
> `ssl или tls (доступно с версии UTM-5.3-002-update16) или auto (доступно с версии UTM-5.3-005-update2, работает с OpenSSL 1.1)`
> 
> напишите в конфигурации **'protocol' => 'auto'**

Спасибо. То что нужно. Извиняюсь за свою невнимательность.

**Comment by tshadrin** [comment]
> 
> 
> > `ssl или tls (доступно с версии UTM-5.3-002-update16) или auto (доступно с версии UTM-5.3-005-update2, работает с OpenSSL 1.1)`
> > напишите в конфигурации **'protocol' => 'auto'**
> 
> Спасибо. То что нужно. Извиняюсь за свою невнимательность.
После обновления в docker контейнере php, при 'protocol' => 'auto' получил ошибку
`Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small`

**Comment by tshadrin** [comment]
> 
> 
> > `ssl или tls (доступно с версии UTM-5.3-002-update16) или auto (доступно с версии UTM-5.3-005-update2, работает с OpenSSL 1.1)`
> > напишите в конфигурации **'protocol' => 'auto'**
> 
> Спасибо. То что нужно. Извиняюсь за свою невнимательность.


После очередного обновления минорной версии php-7.2 в docker контейнере, опять появилось исключение при 'protocol' => 'auto'
`Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small`
Пришлось вручную выставить алгоритм.

**Comment by k-shym** [comment]
> > > `ssl или tls (доступно с версии UTM-5.3-002-update16) или auto (доступно с версии UTM-5.3-005-update2, работает с OpenSSL 1.1)`
> > > напишите в конфигурации **'protocol' => 'auto'**
> > 
> > 
> > Спасибо. То что нужно. Извиняюсь за свою невнимательность.
> 
> После очередного обновления минорной версии php-7.2 в docker контейнере, опять появилось исключение при 'protocol' => 'auto'
> `Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small`
> Пришлось вручную выставить алгоритм.

Стоит проверить версию OpenSSL в docker, подозреваю будет версия ниже 1.1

**Comment by tshadrin** [comment]
> Стоит проверить версию OpenSSL в docker, подозреваю будет версия ниже 1.1

`OpenSSL 1.1.1c  28 May 2019`

в phpinfo соответственно 

`SSL Version | OpenSSL/1.1.1c`

**Comment by k-shym** [comment]
@tshadrin проверил на очень похожих версиях, docker `image: php:7.2-fpm-stretch`, вот результат:
```
# php -v
PHP 7.2.34 (cli) (built: Dec 11 2020 11:22:50) ( NTS )

# openssl 
OpenSSL> version
OpenSSL 1.1.0l  10 Sep 2019
```
```php
$urfa = URFAClient::init([
    'login'    => 'init',
    'password' => 'init',
    'address'  => '127.0.0.1',
    'protocol' => 'auto',
    'api'      => __DIR__ . '/xml/api_53-005.xml',
]);

$result = $urfa->rpcf_liburfa_list();
print_r($result['size'][0]);
```
```
Array
(
    [module] => liburfa-card
    [version] => 5.3-005-update3-debian_jessie_x64
    [path] => liburfa-card
)
```
