### ISSUE TITLE
Поиск по дополнительным параметрам rpcf_search_users_new

### ISSUE THREAD

**Issue by p0s1x** [k-shym/URFAClient#30]
Каким образом, с помощью этой функции, осуществить поиск по дополнительным параметрам?

**Comment by k-shym** [comment]
https://github.com/k-shym/URFAClient/issues/11#issuecomment-271548987

**Comment by altlc** [comment]
Может кому пригодится,  для поиска по доп параметрам нужно взять id параметра прибавить к нему 2147483648 (0x80000000) и полученное значение использовать в качестве what_id
