### ISSUE TITLE
Ошибка Not implemented for PHP x32

### ISSUE THREAD

**Issue by Cramac** [k-shym/URFAClient#7]
пробую сделать смену логина и пароля в утм 5,3
Выполняю такие действия:

```
$service_new['slink_id'] = "11736"; 
$all_service = $urfa->rpcf_get_iptraffic_service_link_ipv6($service_new);
$all_service["ip_groups_count"][0]["iptraffic_login"]="172.30.49.40";
$all_service["ip_groups_count"][0]["iptraffic_password"]="172.30.49.40";
$services_tariff = $urfa->rpcf_edit_iptraffic_service_link_ipv6($all_service);
print_r(URFAClient::trace_log());
```

в итоге получаю такую ошибку:
`[1] => 2016.05.23 14:46:20 ERROR: rpcf_edit_iptraffic_service_link_ipv6( Array ( [tariff_link_id] => 1741 [is_blocked] => 0 [discount_period_id] => 2171 [start_date] => 1392148800 [expire_date] => 2130706431 [policy_id] => 1 [cost_coef] => 1 [unabon] => 0 [unprepay] => 0 [tariff_id] => 73 [parent_id] => 2 [bandwidth_in] => 0 [bandwidth_out] => 0 [ip_groups_count] => Array ( [0] => Array ( [ip_address] => 192.168.0.10 [mask] => 32 [mac] => [iptraffic_login] => 172.30.49.40 [iptraffic_password] => 172.30.49.40 [iptraffic_allowed_cid] => [pool_name] => [ip_not_vpn] => 0 [dont_use_fw] => 0 [is_dynamic] => 0 [router_id] => 0 [switch_id] => 0 [port_id] => 0 [vlan_id] => 0 [pool_id] => 0 ) ) [quotas_count] => Array ( [0] => Array ( [tclass_id] => 0 [tclass_name] => Unknown [quota] => 0.0000000 ) [1] => Array ( [tclass_id] => 10 [tclass_name] => Входящий [quota] => 0.0000000 ) [2] => Array ( [tclass_id] => 20 [tclass_name] => Исходящий [quota] => 0.0000000 ) [3] => Array ( [tclass_id] => 30 [tclass_name] => локальный [quota] => 0.0000000 ) ) ) ): Not implemented for PHP x32`

**Comment by k-shym** [comment]
Посмотрите раздел "Возможные проблемы". В этой функции используется тип данных long, для которого не реализована поддержка в php x32. Переходите на php x64, там такой проблемы не будет.

**Comment by Cramac** [comment]
ок, я так и подумал. Но проблему решил убрав из передаваемого массива, раздел **quotas_count**
