### ISSUE TITLE
rpcf_get_services_list выводит что то не ясное

### ISSUE THREAD

**Issue by Cramac** [k-shym/URFAClient#9]
Есть утм 5,3
пытаюсь вывести список услуг, делаю вызов
rpcf_get_services_list

получаю что то не ясное:

> ```
>         [41] => Array
>             (
>                 [service_id_array] => 162
>                 [service_name_array] => internet
>                 [service_type_array] => 3
>                 [service_comment_array] => 
>                 [service_status_array] => 2
>             )
> ```

```
        [42] => Array
            (
                [service_id_array] => 1433300073
                [service_name_array] => �
                [service_type_array] => 1768846437
                [service_comment_array] => 
                [service_status_array] => 
            )

        [43] => Array
            (
                [service_id_array] => 2
                [service_name_array] => unlim5/250/d
                [service_type_array] => 164
                [service_comment_array] => абон плата
                [service_status_array] => 2
            )

        [44] => Array
            (
                [service_id_array] => 
                [service_name_array] => 
                [service_type_array] => 1970170985
                [service_comment_array] => �
                [service_status_array] => -793718607
            )
```

**Comment by Cramac** [comment]
но в этот список не попадают услуги которые не вхоядт в тарифы (обычная услуга)

**Comment by k-shym** [comment]
Скорее всего они попадают, только неправильно отображаются названия. Причина в том, что все функции описаны по разному, в данной функции используется атрибут set, который не учитывается  данной утилитой. В будущей версии постараюсь учесть. 

А вот временное решение проблемы, вот такое описание было:

> ```
> <function name="rpcf_get_services_list" id="0x2101">
>     <input>
>         <integer name="which_service" default="-1"/>
>     </input>
>     <output>
>         <integer name="services_count"/>
>         <for name="i" from="0" count="services_count">
>             <integer name="service_id_array" array_index="i"/>
>             <string name="service_name_array" array_index="i"/>
>             <integer name="service_type_array" array_index="i"/>
>             <string name="service_comment_array" array_index="i"/>
>             <integer name="service_status_array" array_index="i"/>
>             <set src="service_status_array" src_index="i" dst="service_status"/>
>             <if variable="service_status" value="2" condition="eq">
>                 <string name="tariff_name_array" array_index="i"/>
>             </if>
>             <if variable="service_status" value="2" condition="ne">
>                 <set dst="tariff_name_array" dst_index="i" value=""/>
>             </if>
>         </for>
>     </output>
> </function>
> ```

А вот таким оно должно стать:

> ```
> <function name="rpcf_get_services_list" id="0x2101">
>     <input>
>         <integer name="which_service" default="-1"/>
>     </input>
>     <output>
>         <integer name="services_count"/>
>         <for name="i" from="0" count="services_count">
>             <integer name="service_id_array" array_index="i"/>
>             <string name="service_name_array" array_index="i"/>
>             <integer name="service_type_array" array_index="i"/>
>             <string name="service_comment_array" array_index="i"/>
>             <integer name="service_status" array_index="i"/>
>             <if variable="service_status" value="2" condition="eq">
>                 <string name="tariff_name_array" array_index="i"/>
>             </if>
>             <if variable="service_status" value="2" condition="ne">
>                 <set dst="tariff_name_array" dst_index="i" value=""/>
>             </if>
>         </for>
>     </output>
> </function>
> ```

**Comment by Cramac** [comment]
Спасибо, вроде то что нужно.

**Comment by k-shym** [comment]
Теперь тэг set учитывается.
